### PR TITLE
Human promoter flanking region from Ensembl regulatory build dataset

### PR DESCRIPTION
**Pull request by katarinagresova**

### CODE REVIEW

**Comment by simecek** [comment]
|What is biological significance of promoter flanking region? (do we really want them?)

**Comment by simecek** [comment]
Also, need a check that the length distribution is reasonable and what is CNN classification error.

**Comment by katarinagresova** [comment]
CNN is unable to learn - acc 50%.

**Comment by katarinagresova** [comment]
Not going to use for now

**Pull request closed without merging**
