### PR TITLE
Human ochr ensembl regulatory dataset

### PR DESCRIPTION
**Pull request by katarinagresova**

### CODE REVIEW

**Comment by simecek** [comment]
Check distribution length & train basic CNN (to be sure it can be predicted)

**Comment by katarinagresova** [comment]
CNN is unable to learn. Will not use this dataset.

**Comment by katarinagresova** [comment]
There might be a problem with PyTorch code.

**Comment by katarinagresova** [comment]
Sorry for so many changed files. I needed to rebase main to get code for experiments. 
Files important for this review are:
- [https://github.com/ML-Bioinfo-CEITEC/genomic_benchmarks/blob/human_ochr_ensembl_regulatory/docs/human_ocr_ensembl_regulatory/README.md](https://github.com/ML-Bioinfo-CEITEC/genomic_benchmarks/blob/human_ochr_ensembl_regulatory/docs/human_ocr_ensembl_regulatory/README.md)
- [https://github.com/ML-Bioinfo-CEITEC/genomic_benchmarks/blob/human_ochr_ensembl_regulatory/docs/human_ocr_ensembl_regulatory/create_datasets.ipynb](https://github.com/ML-Bioinfo-CEITEC/genomic_benchmarks/blob/human_ochr_ensembl_regulatory/docs/human_ocr_ensembl_regulatory/create_datasets.ipynb)
- [https://github.com/ML-Bioinfo-CEITEC/genomic_benchmarks/blob/human_ochr_ensembl_regulatory/experiments/tf_cnn_experiments/human_ocr_ensembl_regulatory.ipynb](https://github.com/ML-Bioinfo-CEITEC/genomic_benchmarks/blob/human_ochr_ensembl_regulatory/experiments/tf_cnn_experiments/human_ocr_ensembl_regulatory.ipynb)

I was not able to make PyTorch CNN learn something from this data, but TF got accuracy 73%.

**Pull request merged**
